name: persona_assistant
description: 'Persona Assistant for Persona Games'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: 3.27.0

dependencies:
  flutter:
    sdk: flutter
  catppuccin_flutter: ^1.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.5
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.3
  meta: ^1.16.0
  p3r_data:
    path: ./packages/p3r_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/p3r/jsons/
    - assets/p3r/images/skills/
    - assets/p3r/images/arcana/
