name: persona_data
description: 'The package to manage and generate Persona data'
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  pair: ^0.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/p3r/jsons/
